# Generated by Django 4.2.13 on 2024-06-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_posts", "0003_remove_post_last_edited_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="last_edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
