# Generated by Django 4.2.13 on 2024-06-10 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_posts", "0004_post_last_edited_at"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="last_edited_at",),
    ]
