# Generated by Django 4.2.13 on 2024-06-10 20:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("social_posts", "0006_post_last_edited_at"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="like", unique_together={("post", "user")},
        ),
    ]
