# Generated by Django 4.2.13 on 2024-06-11 13:43

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("social_posts", "0007_alter_like_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
